# Input image to be enhanced
image: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/Images/shipwreck_depth_000606.png"

# Scene properties
distance: 0.33
depth: 6.06
background_sample: [1770, 270, 2, 2]    # x, y, width, height (1 - one point sample)
color_1_sample: [505, 585, 45, 35]  # x, y, width, height (white recommended)
color_2_sample: [1335, 605, 15, 10] # x, y, width, height (black recommended)

# Method
method: 0
is_adaptive: false
optimize: false
est_veiling_light: true

show_image: true
check_time: true

save_data: false
prior_data: false
output_filename: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/output.xml"
input_filename: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/output.xml"
