# Input image to be enhanced
image: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/Images/shipwreck_depth_000606.png"

# Scene properties
distance: 0.33
depth: 0.6
color_1_sample: [505, 585, 45, 35]  # x, y, width, height (white recommended)
color_2_sample: [1335, 605, 15, 10] # x, y, width, height (black recommended)

# Method
method: 0
optimize: false
est_veiling_light: true
# true: average background sample
background_sample: [650, 555, 2, 2]  # x, y, width, height (1 - one point sample)
# false: calculate
camera_response_filename: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/Camera_Response_Files/Sony_IMX322LQJ-C_Camera_Response.csv"
jerlov_water_filename: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/Jerlov_Water/Jerlov_Water_Types.csv"
water_type: "Jerlov I"

show_image: true
check_time: true
log_screen: false

save_data: false
prior_data: false
output_filename: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/escalibr_color.xml"
input_filename: "/home/darobot/Research/color_correct/catkin_ws/src/underwater_color_enhance/escalibr_color.xml"
